/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.views;

import javax.swing.JFrame;

/**
 *
 * @author Administrador
 */
public class vMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public vMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mProveedores = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuPermisos = new javax.swing.JMenuItem();
        mnuModulos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calzado Lobo Solo v.1.0.0");
        setBackground(new java.awt.Color(255, 255, 255));

        mProveedores.setText("Proveedores");
        jMenuBar1.add(mProveedores);

        jMenu2.setText("Pedidos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Compras");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Artículos");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Fichas Técnicas");
        jMenuBar1.add(jMenu6);

        jMenu13.setText("Fracciones");
        jMenuBar1.add(jMenu13);

        jMenu12.setText("Producción");
        jMenuBar1.add(jMenu12);

        jMenu11.setText("Precios y Costos");
        jMenuBar1.add(jMenu11);

        jMenu7.setText("Ventas");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Contabilidad");
        jMenuBar1.add(jMenu8);

        jMenu9.setText("Finanzas");
        jMenuBar1.add(jMenu9);

        jMenu10.setText("Usuarios");

        mnuUsuarios.setText("USUARIOS");
        jMenu10.add(mnuUsuarios);

        mnuPermisos.setText("PERMISOS");
        jMenu10.add(mnuPermisos);

        mnuModulos.setText("MODULOS");
        jMenu10.add(mnuModulos);

        jMenuBar1.add(jMenu10);

        jMenu4.setText("Configuración");
        jMenuBar1.add(jMenu4);

        mSalir.setText("Salir");
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu mProveedores;
    public javax.swing.JMenu mSalir;
    public javax.swing.JMenuItem mnuModulos;
    public javax.swing.JMenuItem mnuPermisos;
    public javax.swing.JMenuItem mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
