/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.views;

import javax.swing.JFrame;

/**
 *
 * @author Administrador
 */
public class vMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public vMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenuItem();
        mnuAlmacenes = new javax.swing.JMenuItem();
        mnuMaquilas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuLineas = new javax.swing.JMenuItem();
        mnuEstilos = new javax.swing.JMenuItem();
        mnuCombinaciones = new javax.swing.JMenuItem();
        mnuMateriales = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuFracciones = new javax.swing.JMenuItem();
        mnuMatxCombinacion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mnuUnidades = new javax.swing.JMenuItem();
        mnuMonedas = new javax.swing.JMenuItem();
        mnuMetodosPago = new javax.swing.JMenuItem();
        mnuCondicionesPago = new javax.swing.JMenuItem();
        mnuBancos = new javax.swing.JMenuItem();
        mnuFamilias = new javax.swing.JMenuItem();
        mnuSeries = new javax.swing.JMenuItem();
        mnuDepartamentos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuPartesZapato = new javax.swing.JMenuItem();
        mnuTemporadas = new javax.swing.JMenuItem();
        mnuHormas = new javax.swing.JMenuItem();
        mnuTiposEstilo = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuPermisos = new javax.swing.JMenuItem();
        mnuModulos = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calzado Lobo Solo v.1.0.0");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jMenu6.setText("Ventas");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Compras");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(jMenu7);

        jMenu2.setText("Fichas Técnicas");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem8.setText("Fichas Técnicas");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Pedidos");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem9.setText("Pedidos");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Producción");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem10.setText("Orden de Producción");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu14.setText("Catálogos");
        jMenu14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuClientes.setText("Clientes");
        mnuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuClientes);

        mnuProveedores.setText("Proveedores");
        mnuProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuProveedores);

        mnuAlmacenes.setText("Almacenes");
        mnuAlmacenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuAlmacenes);

        mnuMaquilas.setText("Maquilas");
        jMenu14.add(mnuMaquilas);
        jMenu14.add(jSeparator3);

        mnuLineas.setText("Lineas");
        mnuLineas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuLineas);

        mnuEstilos.setText("Estilos");
        mnuEstilos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuEstilos);

        mnuCombinaciones.setText("Combinaciones ");
        mnuCombinaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuCombinaciones);

        mnuMateriales.setText("Materiales");
        mnuMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuMateriales);
        jMenu14.add(jSeparator4);

        mnuFracciones.setText("Mano de Obra (Fracciones)");
        mnuFracciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuFracciones);

        mnuMatxCombinacion.setText("Materiales por Combinación");
        mnuMatxCombinacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu14.add(mnuMatxCombinacion);

        jMenuBar1.add(jMenu14);

        jMenu4.setText("Configuración");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setText("Generales");

        mnuUnidades.setText("Unidades");
        mnuUnidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuUnidades);

        mnuMonedas.setText("Monedas");
        mnuMonedas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuMonedas);

        mnuMetodosPago.setText("Métodos de Pago");
        mnuMetodosPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuMetodosPago);

        mnuCondicionesPago.setText("Condiciones de Pago");
        mnuCondicionesPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuCondicionesPago);

        mnuBancos.setText("Bancos");
        mnuBancos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuBancos);

        mnuFamilias.setText("Familias");
        mnuFamilias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuFamilias);

        mnuSeries.setText("Series");
        mnuSeries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuSeries);

        mnuDepartamentos.setText("Departamentos");
        mnuDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuDepartamentos);
        jMenu1.add(jSeparator1);

        mnuPartesZapato.setText("Partes del Zapato");
        mnuPartesZapato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuPartesZapato);

        mnuTemporadas.setText("Temporadas");
        mnuTemporadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuTemporadas);

        mnuHormas.setText("Hormas");
        mnuHormas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuHormas);

        mnuTiposEstilo.setText("Tipos de Estilo");
        mnuTiposEstilo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.add(mnuTiposEstilo);

        jMenu4.add(jMenu1);

        jMenu10.setText("Usuarios");
        jMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.add(mnuUsuarios);
        jMenu10.add(jSeparator2);

        mnuPermisos.setText("Permisos");
        mnuPermisos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.add(mnuPermisos);

        mnuModulos.setText("Módulos");
        mnuModulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.add(mnuModulos);

        jMenu4.add(jMenu10);

        jMenuBar1.add(jMenu4);

        mSalir.setText("Salir");
        mSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    public javax.swing.JMenu mSalir;
    public javax.swing.JMenuItem mnuAlmacenes;
    public javax.swing.JMenuItem mnuBancos;
    private javax.swing.JMenuItem mnuClientes;
    public javax.swing.JMenuItem mnuCombinaciones;
    public javax.swing.JMenuItem mnuCondicionesPago;
    public javax.swing.JMenuItem mnuDepartamentos;
    public javax.swing.JMenuItem mnuEstilos;
    public javax.swing.JMenuItem mnuFamilias;
    public javax.swing.JMenuItem mnuFracciones;
    public javax.swing.JMenuItem mnuHormas;
    public javax.swing.JMenuItem mnuLineas;
    public javax.swing.JMenuItem mnuMaquilas;
    public javax.swing.JMenuItem mnuMateriales;
    public javax.swing.JMenuItem mnuMatxCombinacion;
    public javax.swing.JMenuItem mnuMetodosPago;
    public javax.swing.JMenuItem mnuModulos;
    public javax.swing.JMenuItem mnuMonedas;
    public javax.swing.JMenuItem mnuPartesZapato;
    public javax.swing.JMenuItem mnuPermisos;
    public javax.swing.JMenuItem mnuProveedores;
    public javax.swing.JMenuItem mnuSeries;
    public javax.swing.JMenuItem mnuTemporadas;
    public javax.swing.JMenuItem mnuTiposEstilo;
    public javax.swing.JMenuItem mnuUnidades;
    public javax.swing.JMenuItem mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
